### ISSUE TITLE
Add debug mode and logs

### ISSUE THREAD

**Issue by clmntrss** [michalkvasnicak/aws-lambda-graphql#102]
Hello again, I would like to know if it would be possible to add a debug parameter in the function that would allow to have logs in the Cloudwatch AWS? 

I can possibly look on my side and prepare a PR to add it if you are ok with that.

**Comment by michalkvasnicak** [comment]
@clmntrss what would you like to log?

**Comment by clmntrss** [comment]
@michalkvasnicak  I would like to log 

- A new connection from the user
- When a new Subscription is created
- If an event is discarded why 
- When an event is send to the Subscription
- When an user logout

With some details on the user,subscription and event

**Comment by michalkvasnicak** [comment]
@clmntrss Ok I don't see any problem with optional `debug` flag. Could you prepare a PR ?

**Comment by clmntrss** [comment]
@michalkvasnicak Yes of course. I  could do that in 2 week when I'm back from vacations

**Comment by michalkvasnicak** [comment]
@clmntrss any news about this issue? Would you like to do it?

**Comment by clmntrss** [comment]
Yes it's almost done, I'll make a PR asap.

I added some console.log to view some events in Cloudwatch with a debug flag to enable them
