### ISSUE TITLE
How to integrate with Apollo Server?

### ISSUE THREAD

**Issue by powerfulj** [michalkvasnicak/aws-lambda-graphql#104]
Thanks for developing such an awesome package for us.
I have a stupid question here.

What I want to achieve is that I want to merge this package into our main application which is based on Apollo Server.
In your example, the endpoints are all generated from the "Server" class.
Question is how could I integate it with Apollo Server, is there any sample?

Thanks
CJ

**Comment by michalkvasnicak** [comment]
It already uses `ApolloServer` for HTTP requests because `Server` extends `ApolloServer` from `apollo-server-lambda`, for WebSocket connections it extends it with the handler for WebSocket events.
