### ISSUE TITLE
subscriptions not working properly 

### ISSUE THREAD

**Issue by Adel-ak** [michalkvasnicak/aws-lambda-graphql#105]
Hello michal,

Thank for making such a helpful package, i'm currently facing a minor problem with subscriptions, and here is whats going on.

I'm working on a app, where when a customer creates a new order (A react native application), which will trigger a mutation and then publish a subscription event to our web app (A react application), it successfully triggers and the new order is received and shown in the UI and shown in the event table in dynamodb.

```
const createOrder = async ({ NewOrderInputs }, _ ,{pubSub}) => {
  try {
    const orderNum = await nextOrderNum();
    
    const createdOrder = await new Orders({
      ...NewOrderInputs,
      customerId: "customerId",
      orderNumber: "orderNum",
    });

    createdOrder.save();

    pubSub.publish(NEW_ORDER, {newOrder: createdOrder});

    return createdOrder;
  } catch (error) {
    console.log("newOrderNoAuth -> error", error);
  }
};

```

Now when the web user accepts the new order, a mutation is triggered to change the order status to "Accepted" and publish a subscription event to our user in the RN app, here is when the subscription doesn't do what its suppose to.

```
const changeOrderStatus = async ({OrderStatusInput}, _ ,{pubSub}) => {
  const {status, eta, orderId} = OrderStatusInput;
  try{
    const currentDateAndTime = new Date();
    const estimatedDateAndTime = eta;

    const order = await Orders.findOneAndUpdate({ _id: orderId },{
      timeStampEta : eta ? estimatedDateAndTime : currentDateAndTime,
      orderStatus: status
    },{new:true});

    pubSub.publish(ORDER_STATUS_CHANGED, {orderStatusChanged: order });

    return true
  }catch(error){
    console.log("changeOrderStatus -> error", error)
  }
}
```

The first event is triggered but it doesn't go through as if its stuck mid way and nothing shows up in the RN UI and the event table in dynamodb, then when the same event is triggered with a new order status of "Ready", the first event of order status "Accepted" goes through and shows up in the RN UI as well as the event table in dynamodb, and the last order status of "Completed" gets the Ready event.

I am not sure as to why this happening and your help would be much appreciated.

also this is happening only when its deployed to aws, works properly when the server is running on local .

here is what my subscriptions look like

```
const subscriptions = {
  helloWorldSub: {
    resolve: (rootValue) => rootValue,
    subscribe: (rootValue, args, ctx, info) => ctx.pubSub.subscribe(HELLO_WORLD)(rootValue, args, ctx, info),
  },
  orderStatusChanged: {
    subscribe: withFilter(
      (root, args, ctx, info) => ctx.pubSub.subscribe(ORDER_STATUS_CHANGED)(root, args, ctx, info),
      (payload, variables) =>
        payload.orderStatusChanged.customerId === variables.customerId
    ),
  },
  newOrder: {
    subscribe: withFilter(
      (root, args, ctx, info) => ctx.pubSub.subscribe(NEW_ORDER)(root, args, ctx, info),
      (payload, variables) => payload.newOrder.storeId === variables.storeId
    ),
  },
};
```

**Comment by michalkvasnicak** [comment]
Hey @Adel-ak , please try to append `await` to `pubSub.publish()` because it's async and maybe your event loop closes sooner so `eventStore` won't get a chance to store the event to dynamodb.

Have you checked logs of your functions? I saw this happening in chat app when I deployed buggy version of the server where processing of DynamoDB event stream failed and it caused the stream to pause. Then when I deployed fixed version and published a new message it resumed the stream and the client received all the failed messages + the new one.

**Comment by Adel-ak** [comment]
@michalkvasnicak that worked like a charm, thank you, you saved me from losing my mind.

If i may ask, any idea why it worked fine with the new order subscription and not with the order change subscription, i'm kind of craving for a answer and cant think of any reason.

Also, i think this piece of information will benefit others, if you want i could make a PR and find it a place in the docs.

**Comment by michalkvasnicak** [comment]
@Adel-ak unfortunately I don't know why it worked only for `newOrder` subscription. There can be numerous reasons why. For example if you have some nested resolvers on the result type of `createOrder` mutation that you ask for when you send this mutation, it could cause event loop to last longer and process the published event. But `changeOrderStatus` returned only boolean so maybe the function just finished its lifetime and subsequent call to it maybe flushed the event. Hard to say.

In examples there is always `await pubSub.publish(...)` so I don't think it's necessary to add something to documentation but thank you 🙂 .
