### ISSUE TITLE
How to create an asynchronous server?

### ISSUE THREAD

**Issue by cjnoname** [michalkvasnicak/aws-lambda-graphql#110]
```
const server = new Server({
  connectionManager,
  eventProcessor: new DynamoDBEventProcessor(),
  resolvers,
  subscriptionManager,
  // use serverless-offline endpoint in offline mode
  ...(process.env.IS_OFFLINE
    ? {
        playground: {
          subscriptionEndpoint: 'ws://localhost:3001',
          endpoint: "dev/aqsdass"
        },
      }
    : {}),
  typeDefs,
});

export const handleHttp = server.createHttpHandler();
export const handleWebSocket = server.createWebSocketHandler();
export const handleDynamoDBStream = server.createEventHandler();
```

Hi,

I'm a solution architect from a mid-sized company that has more than 100,000 members around the world.
We decided to use your package on our main product (pure serverless solution).

Above is the copy from your sample code.
The requirement is, we need to create to the apollo server in async way (for db connection and schema generate),  and my developers cannot make it running.

Here is the code they tried but not working:

```
const createServer = async () => {
  // some async code here
  const server = new Server({
    resolvers,
    typeDefs,
    connectionManager,
    eventProcessor: new DynamoDBEventProcessor(),
    subscriptionManager,
  });
  return server;
};

export const handleHttp = (
  event: APIGatewayProxyEvent,
  context: Context,
  callback: Callback<APIGatewayProxyResult>
) => {
  createServer().then((server: any) =>
    server.createHandler({
      cors: {
        origin: "*",
        credentials: true
      }
    })(event, context, callbackFilter)
  );
};

export const handleWebSocket = (event: APIGatewayWebSocketEvent, context: Context) => {
  createServer().then((server) => server.createWebSocketHandler()(event, context));
};

export const handleDynamoDBStream = () => {
  createServer().then((server) => server.createEventHandler());
};
```

Could you help the guys out? 

Thanks
CJ

**Comment by michalkvasnicak** [comment]
I think it should be enough to return a promise from lambda handlers.

```js
export const handleWebSocket = (event: APIGatewayWebSocketEvent, context: Context) => {
  return createServer().then((server) => server.createWebSocketHandler()(event, context));
};

export const handleDynamoDBStream = () => {
  return createServer().then((server) => server.createEventHandler());
};
```

Because from your example Lambda will basically finish immediately.

**Comment by cjnoname** [comment]
> I think it should be enough to return a promise from lambda handlers.
> 
> ```js
> export const handleWebSocket = (event: APIGatewayWebSocketEvent, context: Context) => {
>   return createServer().then((server) => server.createWebSocketHandler()(event, context));
> };
> 
> export const handleDynamoDBStream = () => {
>   return createServer().then((server) => server.createEventHandler());
> };
> ```
> 
> Because from your example Lambda will basically finish immediately.

Thanks for your reply, sorry I didn't get the point.

Could you support a short example? Because our code does work.

Thanks
CJ

**Comment by michalkvasnicak** [comment]
Your code misses `return` in handlers according to code you provided.

```js
const createServer = async () => {
  // some async code here
  const server = new Server({
    resolvers,
    typeDefs,
    connectionManager,
    eventProcessor: new DynamoDBEventProcessor(),
    subscriptionManager,
  });
  return server;
};

export const handleHttp = (
  event: APIGatewayProxyEvent,
  context: Context,
  callback: Callback<APIGatewayProxyResult>
) => {
  // return is missing
  createServer().then((server: any) =>
    server.createHandler({
      cors: {
        origin: "*",
        credentials: true
      }
    })(event, context, callbackFilter)
  );
};

export const handleWebSocket = (event: APIGatewayWebSocketEvent, context: Context) => {
  // return is missing
  createServer().then((server) => server.createWebSocketHandler()(event, context));
};

export const handleDynamoDBStream = () => {
  // return is missing
  createServer().then((server) => server.createEventHandler());
};
```

So it should be:

```js
const createServer = async () => {
  // some async code here
  const server = new Server({
    resolvers,
    typeDefs,
    connectionManager,
    eventProcessor: new DynamoDBEventProcessor(),
    subscriptionManager,
  });
  return server;
};

export const handleHttp = (
  event: APIGatewayProxyEvent,
  context: Context,
  callback: Callback<APIGatewayProxyResult>
) => {
  return createServer().then((server: any) =>
    server.createHandler({
      cors: {
        origin: "*",
        credentials: true
      }
    })(event, context, callbackFilter)
  );
};

export const handleWebSocket = (event: APIGatewayWebSocketEvent, context: Context) => {
  return createServer().then((server) => server.createWebSocketHandler()(event, context));
};

export const handleDynamoDBStream = () => {
  return createServer().then((server) => server.createEventHandler());
};
```

**Comment by cjnoname** [comment]
> Your code misses `return` in handlers according to code you provided.
> 
> ```js
> const createServer = async () => {
>   // some async code here
>   const server = new Server({
>     resolvers,
>     typeDefs,
>     connectionManager,
>     eventProcessor: new DynamoDBEventProcessor(),
>     subscriptionManager,
>   });
>   return server;
> };
> 
> export const handleHttp = (
>   event: APIGatewayProxyEvent,
>   context: Context,
>   callback: Callback<APIGatewayProxyResult>
> ) => {
>   // return is missing
>   createServer().then((server: any) =>
>     server.createHandler({
>       cors: {
>         origin: "*",
>         credentials: true
>       }
>     })(event, context, callbackFilter)
>   );
> };
> 
> export const handleWebSocket = (event: APIGatewayWebSocketEvent, context: Context) => {
>   // return is missing
>   createServer().then((server) => server.createWebSocketHandler()(event, context));
> };
> 
> export const handleDynamoDBStream = () => {
>   // return is missing
>   createServer().then((server) => server.createEventHandler());
> };
> ```
> 
> So it should be:
> 
> ```js
> const createServer = async () => {
>   // some async code here
>   const server = new Server({
>     resolvers,
>     typeDefs,
>     connectionManager,
>     eventProcessor: new DynamoDBEventProcessor(),
>     subscriptionManager,
>   });
>   return server;
> };
> 
> export const handleHttp = (
>   event: APIGatewayProxyEvent,
>   context: Context,
>   callback: Callback<APIGatewayProxyResult>
> ) => {
>   return createServer().then((server: any) =>
>     server.createHandler({
>       cors: {
>         origin: "*",
>         credentials: true
>       }
>     })(event, context, callbackFilter)
>   );
> };
> 
> export const handleWebSocket = (event: APIGatewayWebSocketEvent, context: Context) => {
>   return createServer().then((server) => server.createWebSocketHandler()(event, context));
> };
> 
> export const handleDynamoDBStream = () => {
>   return createServer().then((server) => server.createEventHandler());
> };
> ```

Thanks for your help. Actually yes, my code was wrong. Because I cut some piece of my code to you that missed the return.
But it's not the case.

Finally get it working, it's because:

```
export const dynamoDBStreamHandler = (event: APIGatewayWebSocketEvent, context: Context) =>
  createServer().then((server) => (server.createEventHandler() as any)(event, context));

```

We didn't call the dynamoDBStreamHandler  with event and context. There's a small type error so we need to cover it with "as any"

Now it's working... Tons of thanks!

This is the final code. I think there must be someone else who has the same requirement.

```const createServer = async () => {
  const server = new Server({
    connectionManager,
    eventProcessor: new DynamoDBEventProcessor(),
    resolvers,
    subscriptionManager,
    // use serverless-offline endpoint in offline mode
    ...(process.env.IS_OFFLINE
      ? {
          playground: {
            subscriptionEndpoint: 'ws://localhost:3001',
            endpoint: "dev/aqsdass"
          },
        }
      : {}),
    typeDefs,
  });
  return server;
}

export const handleHttp = async (
  event: any,
  context: any,
) => { 
  return createServer().then(server=>server.createHttpHandler()(event, context));
}
export const handleWebSocket = async (
  event: any,
  context: any,
) => { return createServer().then(server=> server.createWebSocketHandler()(event, context))};
export const handleDynamoDBStream = async (
  event: any,
  context: any,
) =>{return createServer().then(server=>(server.createEventHandler() as any)(event, context))};
```

Thanks again. I'll let you know once we apply it onto our prd. Might ask you more questions in between 👍
