### ISSUE TITLE
Messages in dynamo db, but subscription not working

### ISSUE THREAD

**Issue by chrishoyes** [michalkvasnicak/aws-lambda-graphql#115]
Just to say, this project is great!

We have seen an issue recently whereby entries pop up in dynamo db (in connections, subscriptions, events, and operations) however the messages are not being delivered to the subscription.
A little note on the setup. We left the ttl as default (2 hours) however have not enabled the TTL on the dynamo db tables - which we need to do soon.

We cleared out all the messages from dynamo db, and it started working again.

Is there any reason why this would happen? We have been using the same code, and setup for over a month without any issues.

**Comment by michalkvasnicak** [comment]
@chrishoyes maybe the event processor fails so DynamoDB stream keeps getting stuck on invalid batch? Hard to say, is there anything in your logs for event processor handler?

**Comment by cjnoname** [comment]
Hi @michalkvasnicak,

I got the same issue. My code works perfectly on my local (offline env) but does not work on AWS.
The event table has new records, the trigger is there, the lambda is called and no errors on the cloudwatch.
The dynamo records would be there for a long period of time.

Not sure what is wrong with my code. I'm using Redis(Elasticache) for connectionManager and subscriptionManager.

Here's my code, let me know if there is anything I missed there.

```const subscriptionManager = new RedisSubscriptionManager({
  redisClient
});
const connectionManager = new RedisConnectionManager({
  subscriptions: subscriptionManager,
  apiGatewayManager: process.env.IS_OFFLINE
    ? new ApiGatewayManagementApi({
        endpoint: "http://localhost:3001"
      })
    : undefined,
  redisClient
});

const dynamoDbClient = new DynamoDB.DocumentClient({
  // use serverless-dynamodb endpoint in offline mode
  ...(process.env.IS_OFFLINE
    ? {
        endpoint: "http://localhost:8000"
      }
    : {})
});

const eventStore = new DynamoDBEventStore({
  dynamoDbClient,
  eventsTable: process.env.EVENT_TABLE_NAME
});```

```

    playground:
      process.env.DEPLOYMENT_STAGE &&
      process.env.DEPLOYMENT_STAGE !== "dev" &&
      process.env.DEPLOYMENT_STAGE !== "local"
        ? undefined
        : {
            endpoint: "/graphql",
            subscriptionEndpoint: process.env.IS_OFFLINE ? "ws://localhost:3001" : undefined
          }

```

I'm not quite sure whether I need to put the subscriptionEndpoint there or not.

Thanks

**Comment by michalkvasnicak** [comment]
@cjnoname that's hard to say if there was an error in event processing you should see it in Cloudwatch logs for your DynamoDB stream handler:

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/e3cbe5ee88c0d0cf723260d232dcacc260a8ffec/packages/aws-lambda-graphql/src/DynamoDBEventProcessor.ts#L28

**Comment by cjnoname** [comment]
> log

@michalkvasnicak

I added the log into code by following your way but there seems no error.

Everything works properly except the graphql Subscription endpoint is not hit.

What might cause this issue? Would the item in dynamodb be deleted after successfully processed?

Thanks
