### ISSUE TITLE
should return all subscriptions

### ISSUE THREAD

**Issue by kvhnuke** [michalkvasnicak/aws-lambda-graphql#118]
https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L145

should be `return { value, done: done && value.length === 0 };` as it is possible for the filter to return empty array due all returned results having lower ttl value, however since the `ExclusiveStartKey` not null, it should continue to get more results

also 
https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L294-L296
shouldn't return there due the exact same issue as above, there is no guarantee  Items.length === 0 if LastEvaluated key is not null

**Comment by michalkvasnicak** [comment]
@kvhnuke thanks for the report. I'm not sure if I understand correctly. In first case what do you propose as a way to detect if the iterations is done? You say `value.length === 0` is not enough, should we check if `ExclusiveStartKey` is empty?

In second case we should do the check whether `LastEvaluatedKey` is empty instead of `items.length === 0` ?

**Comment by kvhnuke** [comment]
> @kvhnuke thanks for the report. I'm not sure if I understand correctly. In first case what do you propose as a way to detect if the iterations is done? You say `value.length === 0` is not enough, should we check if `ExclusiveStartKey` is empty?
> 
> In second case we should do the check whether `LastEvaluatedKey` is empty instead of `items.length === 0` ?

first case should return `return { value, done: done && value.length === 0 }` since you already have the  `done` variable I simply used it and it works as intended

yea for the second case you have to check whether `LastEvaluatedKey` is empty

**Comment by michalkvasnicak** [comment]
@kvhnuke released as `1.0.0-alpha.18`. Thank you very much. Please consider moving the information about your project to #106
