### ISSUE TITLE
Adding custom context to resolvers

### ISSUE THREAD

**Issue by samin** [michalkvasnicak/aws-lambda-graphql#12]
It would be nice to have a way to pass a custom context to the resolvers, something like:

```js
const httpHandler = createHttpHandler({
  connectionManager,
  schema,
  context: async ({ event }) => ({
    hello: 'world'
  })
});
```

**Comment by michalkvasnicak** [comment]
@samin yes you are right `execute` already supports it but it's not passed from `createHttpHandler` and `createWsHandler`.

**Comment by michalkvasnicak** [comment]
@samin released as `0.3.0`. You can try it, what is passed to context creator is defined here https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/types/graphql.ts#L12

**Comment by samin** [comment]
@michalkvasnicak woah, you're fast. I've tried it, but it is currently not being passed in `createHttpHandler` and `createWsHandler`:

There are only four parameters, and `context` function is not one of them
https://github.com/michalkvasnicak/aws-lambda-graphql/pull/13/files#diff-5b4e060f11e74bfbc306dde5aa5abadcR60

**Comment by michalkvasnicak** [comment]
@samin Yes fast but wrong 😅, I'm sorry, fixed in #14, released as `0.3.1`, thank you for notice :)

**Comment by samin** [comment]
@michalkvasnicak thanks, awesome lib BTW

**Comment by michalkvasnicak** [comment]
@samin thank you 🙏
