### ISSUE TITLE
connection_terminate isn't handled by protocols and throws error

### ISSUE THREAD

**Issue by fridaystreet** [michalkvasnicak/aws-lambda-graphql#120]
If client.stop() is called in apollo client, the ws sends 'connection_terminate' operation. This isn't handled and throws

'Invalid operation: Only GQL_CONNECTION_INIT,…QL_START or GQL_STOP operations are accepted'

I'm just making a note of this Micahel, when I get time I'll do a PR

**Comment by michalkvasnicak** [comment]
@fridaystreet that'd be great if you do a PR 👍
