### ISSUE TITLE
API Gateway Socket timeout - 2 hours

### ISSUE THREAD

**Issue by syeshchenko** [michalkvasnicak/aws-lambda-graphql#124]
According to AWS Docs: https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html
API Gateway socket max TTL is 2 hours. 
Is this limit still applicable to `aws-lambda-graphql` or there is a workaround?

**Comment by michalkvasnicak** [comment]
After 2 hours you're reconnected.

**Comment by syeshchenko** [comment]
Thank you @michalkvasnicak 
And after the auto-reconnect, you won't lose subscriptions? e.g. no need to set those up again.

**Comment by michalkvasnicak** [comment]
@syeshchenko it comes down to a GraphQL client. I think that Apollo resubscribes active subscriptions automatically. So it's up to clients how to handle that scenario.
