### ISSUE TITLE
Is there any reason that the `graphql` peer dependency is set to 14 as opposed to 15?

### ISSUE THREAD

**Issue by hally9k** [michalkvasnicak/aws-lambda-graphql#135]
Firstly: Thanks for this repo! 😻 

Secondly: The `graphql` peer dependency is set to 14 as opposed to 15, this breaks typescript support as it appears that the ts types were added to the `graphql` package itself in version 15 and `@types/graphql` was deprecated.
My attempts at installing `graphql@14` and `@types/graphql` resulted in type errors.

**Comment by michalkvasnicak** [comment]
The reason is only because during the time this repo was create, 14.x was the latest version.
