### ISSUE TITLE
Do I must to use DynamoDB storage?

### ISSUE THREAD

**Issue by allran** [michalkvasnicak/aws-lambda-graphql#144]
In my project, I don't want to use DynamoDB for storage anymore. I use Prisma to store or query data. Is there a way to move DynamoDB out，and without rewriting the inside code of 'aws-lambda-graphql' ?

**Comment by michalkvasnicak** [comment]
There are interfaces you must implement in order for your storage to work:

**SubscriptionManager**

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/4a2e826668c987a8ab70257ad2eda7e3e3969926/packages/aws-lambda-graphql/src/types/subscriptions.ts#L16

**ConnectionManager**

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/4a2e826668c987a8ab70257ad2eda7e3e3969926/packages/aws-lambda-graphql/src/types/connections.ts#L50

**EventStore**

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/4a2e826668c987a8ab70257ad2eda7e3e3969926/packages/aws-lambda-graphql/src/types/events.ts#L4

**EventProcessor**

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/4a2e826668c987a8ab70257ad2eda7e3e3969926/packages/aws-lambda-graphql/src/types/events.ts#L8
