### ISSUE TITLE
Send the events from other apis

### ISSUE THREAD

**Issue by cjnoname** [michalkvasnicak/aws-lambda-graphql#146]
How could I send the event messages if I want to send a message it from another apis?

For example I have my graphql subscription api running without issues, and I have another backend API takes 40 mins to run a job and I want to send the message after the job is done to all clients. How could I do it?

Thanks

**Comment by michalkvasnicak** [comment]
If you use DynamoDB as a storage then you need to instantiate `DynamoDBEventStore` (with the same dynamodb table as your graphql api uses) and publish an event.

**Comment by michalkvasnicak** [comment]
But I think it's more safe to use `PubSub` + `DynamoDBEventStore`.

```js
import { PubSub, DynamoDBEventStore } from 'aws-lambda-graphql';

const pubSub = new PubSub({
  eventStore: new DynamoDBEventStore()
});

await pubSub.publish('MY_EVENT_NAME', { myPayload: true });
```
