### ISSUE TITLE
Any plans for support apollo server 3?

### ISSUE THREAD

**Issue by fridaystreet** [michalkvasnicak/aws-lambda-graphql#179]
Hi Michael,

Just wondered if this was on your radar at all and if so any sort of timeframe? If not and you're up for a discussion I'd be happy to try and work through a list of requirements/tasks and see if can get a plan of action. And also happy to help with the tasks.

Cheers
Paul

**Comment by michalkvasnicak** [comment]
@fridaystreet unfortunately I don't have a time to work on this library actively so it would be really nice if someone else would take care of this :) 

The plan would be to release current version as `1.0` and the one with Apollo Server 3 as `2.0` if there are any breaking changes.

**Comment by fridaystreet** [comment]
Hi Michael,

Thanks for getting back to me. I must say I haven't really touched it since last year when we implemented it, which is testimont to it being a great library I'd say :-) But yes, we're looking at apollo 3 now. I really like the simplicity of this in keeping it serverless. So far we haven't had any issue with it, it's been running quite happily in production albeit with a few tweaks we made to suit our needs. 

I'll start having a look at what's involved and see if we can move this forward. Maybe we can keep this open as a place holder as I might have some questions if that's ok? I'm sure once we get moving there would be some others on here that would be happy to contribute as well.

Cheers
Paul

**Comment by fridaystreet** [comment]
For reference to anyone finding this. One of our devs has been working on this for our own use and has released a fork. See his comments here in another issue.

https://github.com/michalkvasnicak/aws-lambda-graphql/issues/128#issuecomment-1376379006

Will look at some sort of merge/PR if required
