### ISSUE TITLE
Add ApolloServer implementation

### ISSUE THREAD

**Issue by michalkvasnicak** [michalkvasnicak/aws-lambda-graphql#2]

**Comment by elderapo** [comment]
Any progress on this? I am willing to help if you can point me into the right direction.

**Comment by michalkvasnicak** [comment]
@elderapo Good question. I don't know yet. Basically it should reflect the same usage as is with ApolloServer. But there is a catch that we have to extend the options of apollo server so we can pass our own subscription management, etc.

Maybe something like 

```js
import { ApolloServer } from 'apollo-server';

const server = new ApolloServer({ 
	subscriptionManager: new DynamoDBSubscriptionManager(),
	typeDefs, 
	resolvers,
	// ... other options needed for this package to work
});
```

Maybe it could extend the `ApolloServer`, extend the context with internal details needed for subscription managers to work.

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/execute.ts#L101

Would you like to take a look into this?

**Comment by elderapo** [comment]
I have very little knowledge about apollo server internals. I will check it out in depth tomorrow alongside other implementations that extend apollo server.

Also, I think it would be handy to wait for https://github.com/dherault/serverless-offline/pull/711 so it's easier to test on local.

**Comment by michalkvasnicak** [comment]
Interesting, I'm really not a user of serverless so I don't watch for changes in this ecosystem. But I agree that it could be helpful to test the stuff locally.

**Comment by ganey** [comment]
Sorry to dig this issue up again, but the serverless offline fixes have been merged 🎉

**Comment by michalkvasnicak** [comment]
@ganey thank you for letting me know. I'll take a look into this during #38 work.
