### ISSUE TITLE
Socket disconnect recovery

### ISSUE THREAD

**Issue by niftybit** [michalkvasnicak/aws-lambda-graphql#24]
For your example chat app, I've set Client options to include:
`{   
  reconnect: true,
  reconnectAttempts: Infinity,
  }`

However, when a websocket disconnects (simulated using sleep on mac), all subscriptions are lost and no messages are passed even after reconnecting. Is there a way to remedy this?

**Comment by sammarks** [comment]
I've done a few tests with this - looks like it reconnects the first time successfully, but then when the connection is lost again (mine is being lost because of a 10 minute inactivity limit with API Gateway), it doesn't see the disconnect. Gonna see if I can get a PR up for this...

**Comment by michalkvasnicak** [comment]
Released as `0.7.1`. Thanks to @sammarks for #25
