### ISSUE TITLE
Provide compatibility with serverless-offline

### ISSUE THREAD

**Issue by michalkvasnicak** [michalkvasnicak/aws-lambda-graphql#41]
I think there are maybe just few spots that should be refactored in order to fully support `serverless-offine`. One such spot is Api Gateway management URI.

**Comment by AlpacaGoesCrazy** [comment]
This pull request https://github.com/michalkvasnicak/aws-lambda-graphql/pull/21 builds offline compatibility upon using dynamoDB offline. Maybe we can store connection state, events, etc in memory for offline testing so it will be not so complex to set up (dynamoDB client would need env configuration, installation of additional serverless plugins, etc)? 
The only problem with in memory approach I can see is how could we detect subscription events and trigger publishing.

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy I'd maybe wait until the refactor #38 then it should be easier for developers to quickly set up a project in general (and then it'll be easier to just set up correct DynamoDB URI for usage with `serverless-offline`). 

Correct me if I'm wrong but to achieve full compatibility with `serverless-offline` we just need a way to specify a custom DynamoDB endpoint for `aws-sdk` and a custom Connection Management API endpoint for ApiGateway v2.

**Comment by michalkvasnicak** [comment]
I think we could solve this by introducing new connection and subscription managers and event store that basically invokes the lambda using "api" or something like that.

**Comment by michalkvasnicak** [comment]
This is now done in #59 

It's using DynamoDB local and there is just a little code that needs to be written.
