### ISSUE TITLE
JSON.Stringify event payload

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [michalkvasnicak/aws-lambda-graphql#45]
DynamoDB throws error when you try to store empty strings:
`One or more parameter values were invalid: An AttributeValue may not contain an empty string`
Event data should be serializable anyway, so maybe it will be better to pass it as string to event store so the event store implementation won't interfere with our event?

**Comment by seanchambo** [comment]
👍 I am currently running into this issue as well
