### ISSUE TITLE
Implement TTL mechanism in DynamoDB event store

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [michalkvasnicak/aws-lambda-graphql#47]
Currently event records are stored in DynamoDB indefinitely, maybe events should use [dynamoDB's TTL feature](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html), so they will be eventually deleted and we wont be overcharged for storage of useless events

**Comment by michalkvasnicak** [comment]
Yes that's true. How would you determine the value of TTL field? Configuration value or maybe a function in that could set it based on event type?

**Comment by AlpacaGoesCrazy** [comment]
For events i don't know if there is a point to store event after it was emitted to the subscribers.
For subscriptions and connections [AWS Api Gateway has limitations on connection length](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html). It is 10 minutes for idle connection and 2 hours for any connection. So I guess it will be save to set TTL here for 2 hours as connection will be dropped anyway.

**Comment by michalkvasnicak** [comment]
Yes 2 hours are reasonable. But maybe we could use it as a default and allow users to set the TTL to whatever they want. 

`EventStore` could accept `ttl?: number | (event: any) => number` in constructor.

Where `ttl` is unix timestamp in seconds.

**Comment by AlpacaGoesCrazy** [comment]
2 hours is for connection and subscription manager, for event store I am not sure, as I think we can safely remove event records as soon as they are emmited

**Comment by michalkvasnicak** [comment]
Yes I understand, I'm talking about event stores because they're responsible for publishing events to underlying storage:

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/260333160fa60016ccd24de92cac10025eae8d3b/packages/aws-lambda-graphql/src/types/events.ts#L3

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy Only problem with this is that we can specify TTL for event but it's up on the user to actually specify a TTL on DynamoDB table.

I don't want to somehow create tables on user's behalf. So I'd need to document this library better about the structure of tables etc.

**Comment by ganey** [comment]
Would a cloud-formation template that the user can run be sufficient for handling the dynamoDB table?

Or maybe a block user's could paste into the serverless file for the lambda function?

**Comment by AlpacaGoesCrazy** [comment]
I belive in dynamoDB you enanble TTL feature by enabling a schema field as TTL and after that you provide an an expiration timestamp per each record. So `DynamoDBEventStore` would need to put records with TTL value.
I wonder if TTL mechanism would trigger trigger lambda causing unnecessary lambda invocations.

**Comment by michalkvasnicak** [comment]
Yes it seems that TTL propagates to DynamoDb stream too. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-streams.html 

So this library could be responsible for storing TTL timestamp field on an event but it should be user's responsibility to actually enable this mechanism either by TTL field or some other lambda trigger by interval.

**Comment by michalkvasnicak** [comment]
@AlpacaGoesCrazy as far as I know, lambda will invoke `$disconnect` so we don't need TTL on connections/subscriptions because they should be cleaned up by normal mechanism that is already implemented. 

TTL does make a sense only for events, but there is a problem that it'll invoke
lambda connected to DynamoDb stream.
