### ISSUE TITLE
Publishing to undefined topic breaks dynamoDB trigger

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [michalkvasnicak/aws-lambda-graphql#49]
When you try to publish subscription message like this
```await pubSub.publish(undefined, payload)```
It will allow to publish such message however lambda trigger will throw this error:

> ExpressionAttributeValues must not be empty

Moreover because trigger lambda failed it will try to invoke it again with same parameter creating a loop which is possible to break only when you delete your dynamoDB trigger

I think `event` property should be part of composite key on dynamoDB Events table, and we should throw an error in PubSub when trying to publish event without a topic

**Comment by michalkvasnicak** [comment]
So the solution is to not allow undefined as event name?

What about the `event` property? Why it should be a part of composite key?

**Comment by AlpacaGoesCrazy** [comment]
Well, as we can not have an event without a topic it makes sense to identify events in the database by not only id but topic as well

**Comment by michalkvasnicak** [comment]
What problem does it solve? I mean events are just stored and then processed by stream. There is no querying on them.

**Comment by AlpacaGoesCrazy** [comment]
Well, I think you are correct. Anyway this is library user concern if he decides to make it into composite key
