### ISSUE TITLE
Any way to plugin-in middleware or validationRules?

### ISSUE THREAD

**Issue by RafalWilinski** [michalkvasnicak/aws-lambda-graphql#5]
With things like `express-graphql` you can add middlewares or validationRules e.g. https://github.com/slicknode/graphql-query-complexity.

Is it possible right now? I wasn't able to implement that.

**Comment by michalkvasnicak** [comment]
To add `validationRules` it should be enough to append it ti default validation rules here https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/execute.ts#L71

The same way as it is applied here https://github.com/graphql/express-graphql/blob/master/src/index.js#L209
