### ISSUE TITLE
Unsubscribe all client subscriptions on $disconnect event

### ISSUE THREAD

**Issue by RafalWilinski** [michalkvasnicak/aws-lambda-graphql#6]
Right now the `Subscriptions` table keeps growing endlessly. On websocket `$disconnect` event Lambda should remove all related subscription records. 

I can implement that if you could point me to a possible solution.

**Comment by michalkvasnicak** [comment]
There is a todo for that in code but I haven't had time to fix that. I'll probably start to work with this library more actively in few weeks but for now if you really need that to be fixed you can take a look here https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBConnectionManager.ts#L96.

Basically we need to delete all records in subscription table that are assigned to connection ID. But there is a problem, it seems that I designed the table poorly so there is a problem how to do that properly.

Hash key is event name and range key is string containing connection id and operationId. We need to find for every event if there is a record that starts with connection id and delete those records.

**Comment by michalkvasnicak** [comment]
My idea is to introduce another table that will track all subscriptions by client and use DynamoDB transactions to manipulate with tables.

As this library is not really production ready yet the API can change and I plan to use it in production in few weeks so I'll work on it more actively.

If you want you can take a look on this or just wait :)

**Comment by RafalWilinski** [comment]
For now I came up with this temporary workaround https://github.com/RafalWilinski/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/DynamoDBSubscriptionManager.ts#L116

**Comment by michalkvasnicak** [comment]
Yes it looks like already sufficient solution. I would recommend using `batchWriteItem` to batch delete operations so you don't need to do that in cycle. 

There is only one possible edge case and that's it if you have more subscriptions than page size so you need to paginate `scan` too.

Also it would be nice to add unsubscribe to client too, so we don't send unnecessary events to client's that subscribed to some event in a view but then transitioned to different view that doesn't need previous subscription.
