### ISSUE TITLE
Exceeding the maximum request items sent to DynamoDB when cleaning up stale connections

### ISSUE THREAD

**Issue by alvinypyim** [michalkvasnicak/aws-lambda-graphql#60]
As in the title.

After processing an event, the Lambda function will publish the result to the connections.  For the connections that are stale (e.g. disconnected from the client silently), the Lambda function will remove the connection and unsubscribe all the subscriptions by removing the records from the DynamoDB tables.  When there are 13 or more subscriptions, there will more than 25 request items sent which exceeds the maximum items defined by AWS, and that causes an error.

In addition, the default number of retry attempt is 10,000 for this type of Lambda invocation.  That means whenever this error occur, it would be retrying for 10,000 times and that would probably result a hefty AWS bill.

**Comment by seanchambo** [comment]
Can we get a patch release for this off v0.12?

**Comment by seanchambo** [comment]
Or even v0.13

**Comment by michalkvasnicak** [comment]
@seanchambo sorry for the late response. I'll look into this later today.

**Comment by michalkvasnicak** [comment]
@seanchambo released as `0.13.1` in `legacy` dist tag.
