### ISSUE TITLE
Serverless offline does not track hot reload changes

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [michalkvasnicak/aws-lambda-graphql#62]
Steps to reproduce:
1. Open and start up server and app example.
2. Change something in server while sls offline is running. For example:
```js
const server = new Server({
  connectionManager,
  eventProcessor: new DynamoDBEventProcessor(),
  resolvers,
  subscriptionManager,
  typeDefs,
  context: () => {
    console.log('test')
    return {}
  }
});
```
3. Serverless offline webpack will rebuild the server application.
4. Reload client application.

Expected behavior:
'test' will be output in sls console when client reconnects
Actual behavior:
nothing is output to console and no changes to the code affect running application.

If you stop serverless offline and restart changes to the code will take effect.

version: 1.0.0-alpha.1

**Comment by michalkvasnicak** [comment]
This is not really a bug with package but rather the problem with `chat-example-server` serverless configuration. (there is serverless-webpack plugin used to compile the app).

**Comment by AlpacaGoesCrazy** [comment]
Well, my project where I use aws-lambda-graphql has the same problem with serverless-webpack, however without aws-lambda-graphql hot reload works just fine

**Comment by michalkvasnicak** [comment]
Does your project work correctly if you instantiate some class in a module scope the same way as `Server` is instantiated?

Isn't this somehow related to this that everything is being invalidated except the handler file?

**Comment by AlpacaGoesCrazy** [comment]
Isn't it the same as instantiating `ApolloServer` from apollo-server-lambda?
This works just fine with serverless-webpack

**Comment by michalkvasnicak** [comment]
You are right it is the same. But the problem is weird because Server just extends the Apollo one. Is this problem related to both HTTP and WebSocket handlers? Because HTTP handler is processed using Apollo's handler and websocket is custom.

**Comment by AlpacaGoesCrazy** [comment]
Only websocket part is affected

**Comment by AlpacaGoesCrazy** [comment]
Well, seems like it is the problem of serverless-offline plugin
https://github.com/dherault/serverless-offline/issues/764

**Comment by michalkvasnicak** [comment]
Thank you for investigating 👍
