### ISSUE TITLE
[Question] Is it possible to use it with Netlify functions?

### ISSUE THREAD

**Issue by carolina-cascade** [michalkvasnicak/aws-lambda-graphql#66]
I have our Apollo server running on Netlify functions, after a disastrous implementation on AppSync and Amplify. Using the AWS Data API the server/Netlify function can interact with a DynamoDB and a Postgresql databases on AWS. Now I need to add subscriptions, and my search got me here. I followed the example and got a deployed stack in AWS, but only at the end I realized my existing Netlify Function was deployed as a new Lambda. Moving back to the AWS environment is something we would really like to avoid.

 Since the demo https://chat-example-app.netlify.com/ is deployed in Netlify, could it be that it is running too on a Netlify function? If so, how the managers and store should be configured to get access to the other AWS resources?

Thank you,

**Comment by michalkvasnicak** [comment]
@carolina-cascade unfortunately I'm not sure if it can be run as netlify function (it can be run but you need api gateway v2 to handle websockets and I'm not sure if netlify support websockets in some way). 

The demo app is deployed separately as client and server. Server is deployed directly to AWS and client app is deployed to netlify.

**Comment by carolina-cascade** [comment]
Thank you, @michalkvasnicak . I had high hopes because Netlify functions are AWS lambdas, but it was too good to be true.
