### ISSUE TITLE
$connect and GQL_CONNECT in quick succession fail with setup

### ISSUE THREAD

**Issue by nenti** [michalkvasnicak/aws-lambda-graphql#67]
The current setup of creating the connection entry into the dynamodb table on $connect and then relying on it to be there on the GQL_CONNECT results in non deterministic connection failures and disconnects because of a ConnectionNotFoundError on the GQL_CONNECT call.

`[offline] connect:ck68ih4ee000065p6323weeu2
handleSubSockets CONNECT $connect no body 2020-02-04T23:25:37.291Z
[offline] action:$default on connection=ck68ih4ee000065p6323weeu2
handleSubSockets MESSAGE $default connection_init 2020-02-04T23:25:37.300Z
{ ConnectionNotFoundError: Connection ck68ih4ee000065p6323weeu2 not found
    at DynamoDBConnectionManager.hydrateConnection (/home/circleci/repo/node_modules/aws-lambda-graphql/src/DynamoDBConnectionManager.ts:69:13)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'ConnectionNotFoundError' }
[offline] action:$default on connection=ck68ih4ee000065p6323weeu2
handleSubSockets MESSAGE $default start 2020-02-04T23:25:37.400Z
[offline] got POST to http://localhost:3001/@connections/ck68ih4ee000065p6323weeu2
[offline] sent data to connection:ck68ih4ee000065p6323weeu2
Serverless: [AWS apigatewaymanagementapi 200 0.006s 0 retries] postToConnection({ ConnectionId: 'ck68ih4ee000065p6323weeu2',
  Data:
   '{"type":"error","payload":{"message":"Prohibited connection!"}}' })
[offline] got DELETE to http://localhost:3001/@connections/ck68ih4ee000065p6323weeu2
[offline] closed connection:ck68ih4ee000065p6323weeu2
Serverless: [AWS apigatewaymanagementapi 200 0.003s 0 retries] deleteConnection({ ConnectionId: 'ck68ih4ee000065p6323weeu2' })
[offline] disconnect:ck68ih4ee000065p6323weeu2
handleSubSockets DISCONNECT $disconnect no body 2020-02-04T23:25:37.435Z`

**Comment by michalkvasnicak** [comment]
@nenti isn't this a problem with serverless offline? Because from my understanding AWS ApiGateway won't send message to your lambda until $connect phase is resolved.

**Comment by nenti** [comment]
Yes this is with Serverless offline and a Apollo-subscription-ws client. That is good to know. Although offline is quite important. My suggestion would be to move the retry logic in the GQL_CONNECT to the query of getting a connection aswell to resolve this then.

Mobile mail, excuse typos.

________________________________
Von: Michal Kvasničák <notifications@github.com>
Gesendet: Mittwoch, Februar 5, 2020 9:23 AM
An: michalkvasnicak/aws-lambda-graphql
Cc: Tobias Nentwig; Mention
Betreff: Re: [michalkvasnicak/aws-lambda-graphql] $connect and GQL_CONNECT in quick succession fail with setup (#67)


@nenti<https://github.com/nenti> isn't this a problem with serverless offline? Because from my understanding AWS ApiGateway won't send message to your lambda until $connect phase is resolved.

**Comment by michalkvasnicak** [comment]
Closed by #68
