### ISSUE TITLE
Add a way to unsubscribe Client from subscription

### ISSUE THREAD

**Issue by michalkvasnicak** [michalkvasnicak/aws-lambda-graphql#7]

**Comment by dannysood** [comment]
any update on this?

**Comment by michalkvasnicak** [comment]
I'll try and take a look on this issue today or tomorrow.

**Comment by michalkvasnicak** [comment]
Released in `0.6.0`. It is a breaking change, you need to update stack so there is `SubscriptionOperations` DynamoDB table (in case DynamoDB is used as backend).

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/serverless.yml#L94

or 

https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/cloudformation.yml#L37
