### ISSUE TITLE
Subscription field must return Async Iterable. Received: [function]

### ISSUE THREAD

**Issue by fridaystreet** [michalkvasnicak/aws-lambda-graphql#73]
I'm getting the below error when trying to subscribe. 

Error: Subscription field must return Async Iterable. Received: [function]
    at /Users/paul/development/aleign/graphql-backend/node_modules/graphql/subscription/subscribe.js:169:13

I'm not sure it's necessarily an issue with this library directly, but what I think is going on is that the pubsub.subscribe function from this library is returning a promise which resolves to the asyncIterator. So I've tried to wrap my subscribe function in resolver with async and await pubsub.subscribe('event'), then return the asynIterator

Subscription: {
    trackerAdded: {
      // Additional event labels can be passed to asyncIterator creation
      subscribe: async (root, args, { pubsub }, session) => {
        const asyncIterator = await pubsub.subscribe([`TRACKER_ADDED`]);
        return asyncIterator;
      }
    }
  }

but I still get the error, so I'm guessing graphql-subscriptions isn't liking being handed a promise and the [function] it's referring to in the error is in fact a promise.

I'm also using graphql-modules so at this stage not sure if that's getting in the way. 

Has anyone had any issues passing the promise back in the subscribe function?

Cheers
Paul

**Comment by fridaystreet** [comment]
scratch that, just realised I obviously didn't read the updated doco properly when moving to new version. Wasn't passing the args on the end as per below

`Subscription: {
    trackerAdded: {
      
      subscribe: async (root, args, context, info) => context.pubsub.subscribe([`TRACKER_ADDED`])(root, args, context, info)
    }
  }`

**Comment by maxweba** [comment]
My problem was that the local dynamo wasn't installing, so I had to create a script.
`const dynamodbLocal = require('dynamodb-localhost');
dynamodbLocal.install(() => {
  console.log('------- Finish -------');
}, '../../../.dynamodb');`
