### ISSUE TITLE
Update Docs to reflect the code example

### ISSUE THREAD

**Issue by IslamWahid** [michalkvasnicak/aws-lambda-graphql#74]
I see the main README is not updated as the current code example and it's quite confusing that you don't know which one is the correct one. e.g. the dynamodb-local part in the code example it's initialized for local development and that's not mentioned in the README

**Comment by michalkvasnicak** [comment]
@IslamWahid could you please point me to the specific parts of readme where it's wrong? From your description I don't know exactly where is the problem.

**Comment by michalkvasnicak** [comment]
The server example should work with and without serverless offline. Basically only thing that should be changing the logic is `process.env.IS_OFFLINE` environment variable, otherwise there is nothing that should mess up with the code that it won't run on AWS.
