### ISSUE TITLE
Why do I need two subscription dynamodb tables?

### ISSUE THREAD

**Issue by zhaoyi0113** [michalkvasnicak/aws-lambda-graphql#80]
I see it uses two subscription tables: `SubscriptionOperations` and `Subscriptions`. Why do I need two of them? Can I combine them into one?

**Comment by michalkvasnicak** [comment]
@zhaoyi0113 there is nothing forcing you to use both of them. You can implement your own subscription manager by implementing the [`ISubscriptionManager`](https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/types/subscriptions.ts#L16)

**Comment by zhaoyi0113** [comment]
cool thanks for that information
