### ISSUE TITLE
How can I call the lambda from another lambda?

### ISSUE THREAD

**Issue by zhaoyi0113** [michalkvasnicak/aws-lambda-graphql#81]
I have tried your library and it works great. One question I have is how I can call the graphql lambda function from another lambda? I can only send `query` `mutation` through API gateway but I don't know how to pass the event from lambda function. 

The reason I want to call the graphql lambda from another lambda is to publish event for subscribers. One of my lambda is listening on an event from an external service and it needs to publish the event to all subscribers in the graphql. 

Does this library support this?

**Comment by michalkvasnicak** [comment]
@zhaoyi0113 publishing with DynamoDB store is based on DynamoDB stream. So when you write something to event table, then it's automatically picked by lambda function that processes events and sends them to Api Gateway.

You don't need to call the lambda using GraphQL. You just need to instantiate `PubSub` with correct `DynamoDBEventStore` instance.

- instantiation: https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/src/index.ts#L25
- publishing the event: https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/src/index.ts#L87

**Comment by michalkvasnicak** [comment]
So basically both lambdas should have the instance with same `event store`. Lambda that publishes message, will send events directly to event store and the lambda that handles GraphQL subscriptions and works as event processor will pick them up and sent to correct connections.

**Comment by zhaoyi0113** [comment]
That makes sense. Thanks.

**Comment by zhaoyi0113** [comment]
There is one thing I don't understand is that the lambda is short lived. It doesn't persist event store instance. In the demo, it uses dynamodb to store the event in event store. How is the lambda triggered by dyanmodb? Does it use dynamodb streaming? If yes, the lambda needs to handle events from both API gateway and dynamodb streaming, right?
If I implement a event store which is not using dynamodb, how can I make it work?

**Comment by michalkvasnicak** [comment]
1. event handling is this handler https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/src/index.ts#L134
2. GraphQL over WebSocket https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/src/index.ts#L133 
3. GraphQL over HTTP https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/src/index.ts#L132

Lambda is triggered by DynamoDB event stream as I mentioned above. If you want to implement your own event store, make sure that the source is able to invoke AWS Lambda (e.g. Kinesis, ...) or you'll need to implement some custom logic that will invoke your lambda with events to process.
