### ISSUE TITLE
Can't use the first function inside `withSync`

### ISSUE THREAD

**Issue by zhaoyi0113** [michalkvasnicak/aws-lambda-graphql#82]
I have a subscription has `withFilter` working as below:

```
subscribe: withFilter(
        pubSub.subscribe('TRANSACTION_REQUEST'),
        (payload: any, variables: any) => {
          return payload.transactionId === variables.transactionId;
        },
      ),
```

the above code works fine. But if I change the first parameter to a function like below:

```
subscribe: withFilter(
        (root: any, args: any) => {
          console.log('req txn with filter args', args);
          return pubSub.subscribe('TRANSACTION_REQUEST') as any;
        },
        (payload: any, variables: any) => {
          return payload.transactionId === variables.transactionId;
        },
      ),
```
I will get below error:

```
2020-06-01T12:39:20.897Z	c553cfff-e31f-4c99-b768-a2f7d3d599db	INFO	TypeError: asyncIterator.next is not a function
    at getNextPromise (/opt/nodejs/node_modules/aws-lambda-graphql/dist/withFilter.js:8:34)
    at Object.next (/opt/nodejs/node_modules/aws-lambda-graphql/dist/withFilter.js:23:24)
    at Object.next (/opt/nodejs/node_modules/graphql/subscription/mapAsyncIterator.js:55:23)
    at /opt/nodejs/node_modules/aws-lambda-graphql/dist/DynamoDBEventProcessor.js:79:59
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 47)
    at async /opt/nodejs/node_modules/aws-lambda-graphql/dist/DynamoDBEventProcessor.js:90:25
```

It seems that the return value is not correct. I wonder what return value I should use. In `ApolloServer`, it uses the method `pubsub.asyncIterator` but I can't find this method in your `PubSub` class. How can I return the value in the first function?

**Comment by michalkvasnicak** [comment]
`PubSub.subscribe` returns a function https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/PubSub.ts#L25.

Given this fact, your second example should be:

```
subscribe: withFilter(
        (root: any, args: any, context: any) => {
          console.log('req txn with filter args', args);
          return pubSub.subscribe('TRANSACTION_REQUEST')(root, args, context;
        },
        (payload: any, variables: any) => {
          return payload.transactionId === variables.transactionId;
        },
      ),
```

**Comment by michalkvasnicak** [comment]
See the test case for `PubSub` https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/__tests__/PubSub.test.ts#L27 and also test schema fixture https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/aws-lambda-graphql/src/fixtures/schema.ts#L87

**Comment by michalkvasnicak** [comment]
Looking at your code, it seems you're already using typescript, so you should get an error from typecheck.

**Comment by zhaoyi0113** [comment]
Yes, that's right. Your proposal works for me thanks.
